
mybatis:
  mapper-locations: classpath:**/*Mapper.xml
  type-aliases-package: fun.lianys.blogserver.model.entity.*
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_lian
    username: root
    password: tb1766318380
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  devtools:
    livereload:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: liuli api
  try-host: http://localhost:${server.port}
server:
  port: 8090
  servlet:
    context-path: /api/blog
logging:
  file:
    name: blog.log

# 自定义的一些配置
file.upload.path: files/
cos.secretId: AKIDymKbcMq2yd18yXpqa4HTVMxHK6bpmSr0
cos.secretKey: sUpthEUTBbkcCVXImzvay4tRiiRs2wZv
